// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	interact "work/biz/router/interact"
	relation "work/biz/router/relation"
	test "work/biz/router/test"
	user "work/biz/router/user"
	video "work/biz/router/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	test.Register(r)

	relation.Register(r)

	interact.Register(r)

	video.Register(r)

	user.Register(r)

}
