// Code generated by hertz generator.

package test

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testMw() []app.HandlerFunc {
	// your code...
	return nil
}
