// Code generated by hertz generator.

package video

import (
	"work/biz/router/authfunc"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videofeedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videolistMw() []app.HandlerFunc {
	// your code...
	return authfunc.Auth()
}

func _popularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopopularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return authfunc.Auth()
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosearchMw() []app.HandlerFunc {
	// your code...
	return authfunc.Auth()
}

func _videopublishcompleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopublishstartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopublishuploadingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videopublishcancleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videovisitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _visitMw() []app.HandlerFunc {
	// your code...
	return nil
}
