// Code generated by hertz generator.

package main

import (
	"work/biz/dal"
	"work/biz/mw/elasticsearch"
	"work/biz/mw/jwt"
	qiniuyunoss "work/pkg/qiniuyun_oss"
	"work/pkg/utils/dustman"
	"work/pkg/utils/syncman"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	elasticsearch.Init()
	dal.Init()
	jwt.AccessTokenJwtInit()
	jwt.RefreshTokenJwtInit()
	qiniuyunoss.OssInit()
	dustman.NewRedisDustman().Run()
	dustman.NewFileDustman().Run()
	syncman.NewVideoSyncman().Run()
	syncman.NewCommentSyncman().Run()
	h := server.Default(server.WithHostPorts(`:10001`))
	register(h)

	h.Spin()
}
