// Code generated by hertz generator.

package main

import (
	"bytes"
	"io/ioutil"
	"log"
	"testing"
	"work/biz/mw/jwt"
	cfgloader "work/pkg/utils/cfg_loader"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/test/assert"
	"github.com/cloudwego/hertz/pkg/common/ut"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

/*
func Test_main(t *testing.T) {
	tests := []struct {
		name string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			main()
		})
	}
}
*/

func hInit() *server.Hertz {
	log.SetOutput(ioutil.Discard)
	hlog.SetOutput(ioutil.Discard)
	cfgloader.Run()
	jwt.AccessTokenJwtInit()
	jwt.RefreshTokenJwtInit()
	h := server.Default()
	register(h)
	return h
}

func BenchmarkPing(b *testing.B) {
	b.StopTimer()
	h := server.Default()
	b.StartTimer()
	ut.PerformRequest(h.Engine, "GET", "/ping", &ut.Body{Body: bytes.NewBufferString("1"), Len: 1},
		ut.Header{Key: "Connection", Value: "close"})
}

func TestUserRegister(t *testing.T) {
	h := hInit()
	req := `{
		"username":"test",
		"password":"123456789"
	}
	`
	ut.PerformRequest(h.Engine, "POST", "/user/register/", &ut.Body{Body: bytes.NewBufferString(req), Len: len(req)},
		ut.Header{Key: `Content-Type`, Value: `application/json`},
	)
}

func BenchmarkUserRegister(b *testing.B) {
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	req := `{
		"username":"test",
		"password":"123456789"
	}
	`
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "POST", "/user/register/", &ut.Body{Body: bytes.NewBufferString(req), Len: len(req)},
			ut.Header{Key: `Content-Type`, Value: `application/json`},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkUserLoginNoMFA(b *testing.B) {
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	req := `{
		"username":"test",
		"password":"123456789"
	}`
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "POST", "/user/login/", &ut.Body{Body: bytes.NewBufferString(req), Len: len(req)},
			ut.Header{Key: `Content-Type`, Value: `application/json`},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkUserLoginMFA(b *testing.B) {
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	req := `{
		"username":"cyk",
		"password":"123456789",
		"code":"123456"
	}`
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "POST", "/user/login/", &ut.Body{Body: bytes.NewBufferString(req), Len: len(req)},
			ut.Header{Key: `Content-Type`, Value: `application/json`},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkUserInfo(b *testing.B) {
	token := `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDMxODg5LCJvcmlnX2lhdCI6MTcxMTAyODI4OX0.gCpVOMoKmDS4iEzzl2ZKlxKwM9ivBX8XBWqsoS5h1GQ`
	uid := `10005`
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "GET", `/user/info/?token=`+token+`&user_id=`+uid, nil)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkVideoFeed(b *testing.B) {
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "GET", `/video/feed/`, nil)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkVideoList(b *testing.B) {
	const (
		uid      = `10003`
		pagenum  = `0`
		pagesize = `10`
		token    = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDMxODg5LCJvcmlnX2lhdCI6MTcxMTAyODI4OX0.gCpVOMoKmDS4iEzzl2ZKlxKwM9ivBX8XBWqsoS5h1GQ`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "GET", `/video/feed/?user_id=`+uid+`&page_num=`+pagenum+`&page_size=`+pagesize, nil,
			ut.Header{Key: "Access-Token", Value: token},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkVideoPopular(b *testing.B) {
	const (
		pagenum  = `0`
		pagesize = `10`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "GET", `/video/popular/?page_num=`+pagenum+`&page_size=`+pagesize, nil)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkVideoSearch(b *testing.B) {
	const (
		token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDMxODg5LCJvcmlnX2lhdCI6MTcxMTAyODI4OX0.gCpVOMoKmDS4iEzzl2ZKlxKwM9ivBX8XBWqsoS5h1GQ`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	req := `{
		"page_num":0,
		"page_size":10
	}`
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "POST", `/video/search/`, &ut.Body{Body: bytes.NewBufferString(req), Len: len(req)},
			ut.Header{Key: "Access-Token", Value: token},
			ut.Header{Key: `Content-Type`, Value: `application/json`},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkLikeAction(b *testing.B) {
	const (
		token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDMxODg5LCJvcmlnX2lhdCI6MTcxMTAyODI4OX0.gCpVOMoKmDS4iEzzl2ZKlxKwM9ivBX8XBWqsoS5h1GQ`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	req := `{
		"video_id":"10003",
		"action_type":"1"
	}`
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "POST", `/like/action/`, &ut.Body{Body: bytes.NewBufferString(req), Len: len(req)},
			ut.Header{Key: "Access-Token", Value: token},
			ut.Header{Key: `Content-Type`, Value: `application/json`},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkLikeList(b *testing.B) {
	const (
		pagenum  = `0`
		pagesize = `10`
		uid      = `10004`
		token    = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDMxODg5LCJvcmlnX2lhdCI6MTcxMTAyODI4OX0.gCpVOMoKmDS4iEzzl2ZKlxKwM9ivBX8XBWqsoS5h1GQ`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "GET", `/like/list/?page_num=`+pagenum+`&page_size=`+pagesize+`&user_id=`+uid, nil,
			ut.Header{Key: "Access-Token", Value: token},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkCommentList(b *testing.B) {
	const (
		pagenum  = `0`
		pagesize = `10`
		vid      = `10003`
		token    = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDMxODg5LCJvcmlnX2lhdCI6MTcxMTAyODI4OX0.gCpVOMoKmDS4iEzzl2ZKlxKwM9ivBX8XBWqsoS5h1GQ`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "GET", `/comment/list/?page_num=`+pagenum+`&page_size=`+pagesize+`&video_id=`+vid, nil,
			ut.Header{Key: "Access-Token", Value: token},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkRelationAction(b *testing.B) {
	const (
		token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDM2NTY4LCJvcmlnX2lhdCI6MTcxMTAzMjk2OH0.Tcg4oZyUm-p3e-24OPpcsjqgM4frEmmhQ8HyItvU4tc`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	req := `{
		"to_user_id":"10003",
		"action_type":0
	}`
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "POST", `/relation/action/`, &ut.Body{Body: bytes.NewBufferString(req), Len: len(req)},
			ut.Header{Key: "Access-Token", Value: token},
			ut.Header{Key: `Content-Type`, Value: `application/json`},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkFollowingList(b *testing.B) {
	const (
		uid   = `10003`
		token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDM2NTY4LCJvcmlnX2lhdCI6MTcxMTAzMjk2OH0.Tcg4oZyUm-p3e-24OPpcsjqgM4frEmmhQ8HyItvU4tc`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "GET", `/following/list/?user_id=`+uid, nil,
			ut.Header{Key: "Access-Token", Value: token},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}

func BenchmarkFriendList(b *testing.B) {
	const (
		uid   = `10003`
		token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW5fZmllbGQiOnsiVWlkIjoiMTAwMDQifSwiZXhwIjoxNzExMDM2NTY4LCJvcmlnX2lhdCI6MTcxMTAzMjk2OH0.Tcg4oZyUm-p3e-24OPpcsjqgM4frEmmhQ8HyItvU4tc`
	)
	b.StopTimer()
	h := hInit()
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		w := ut.PerformRequest(h.Engine, "GET", `/friend/list/?user_id=`+uid, nil,
			ut.Header{Key: "Access-Token", Value: token},
		)
		assert.DeepEqual(b, consts.StatusOK, w.Result().StatusCode())
	}
}
